//
// Created by tvl on 14-04-20.
// Note that this is a header that is automatically generated by CMake;
// the content is derived from cmake/geoviz_test_config.h.in
//

#ifndef CMAKE_GEOVIZ_TEST_CONFIG_H
#define CMAKE_GEOVIZ_TEST_CONFIG_H

// The configured options and settings for GeoViz unit tests from CMake.

#define GEOVIZ_TEST_DIR "/storage/GeoViz/src/../test"

#endif //CMAKE_GEOVIZ_TEST_CONFIG_H
